const bradleyChapterMCQs = {
  "1. Diagnosis of Neurological Disease": [
    { "question": "What is the most important initial goal when evaluating a patient with a neurological complaint?", "optionA": "Identify the exact disease immediately", "optionB": "Determine the likely anatomical localization", "optionC": "Order MRI of the brain", "optionD": "Perform extensive laboratory investigations", "correctAnswer": "B" },
    { "question": "A patient presents with sudden-onset hemiplegia. Which feature of the history is particularly useful in determining the underlying pathophysiology?", "optionA": "Marital status", "optionB": "Mode and timing of onset", "optionC": "Educational level", "optionD": "Dietary habits", "correctAnswer": "B" },
    { "question": "According to the diagnostic approach described in the chapter, which sequence best represents neurological diagnosis?", "optionA": "Investigation → diagnosis → examination → history", "optionB": "History → investigation → localization → examination", "optionC": "Chief complaint → localization → possible pathophysiologies → history/examination → differential diagnosis", "optionD": "Examination → treatment → localization → investigation", "correctAnswer": "C" },
    { "question": "A patient reports \u201cnumbness\u201d of one limb. The neurologist should first determine whether the patient actually means sensory loss because:", "optionA": "Patients always exaggerate sensory symptoms", "optionB": "Neurological terminology may be interpreted differently by patients and physicians", "optionC": "Sensory symptoms are never diagnostically useful", "optionD": "Numbness always indicates peripheral neuropathy", "correctAnswer": "B" },
    { "question": "Which of the following is an example of a symptom that strongly suggests a particular temporal pattern of disease?", "optionA": "Gradually progressive weakness over months", "optionB": "Sudden onset of hemiplegia", "optionC": "Long-standing back pain", "optionD": "Chronic tremor", "correctAnswer": "B" },
    { "question": "A patient has weakness of the left arm and leg with increased tone and brisk reflexes. Which principle should guide the next diagnostic step?", "optionA": "Determine the patient's expectations first", "optionB": "Establish anatomical localization", "optionC": "Order genetic testing immediately", "optionD": "Diagnose the most common neurological disease", "correctAnswer": "B" },
    { "question": "A patient has left homonymous hemianopia. This finding most strongly suggests a lesion:", "optionA": "Anterior to the optic chiasm", "optionB": "In the optic nerve", "optionC": "Posterior to the optic chiasm", "optionD": "In the retina", "correctAnswer": "C" },
    { "question": "A patient has a left central scotoma in one eye and weakness of the right limbs. According to the localization approach, this combination suggests involvement of:", "optionA": "Right cerebral hemisphere only", "optionB": "Left optic pathway and left cerebral hemisphere", "optionC": "Left optic nerve and right cerebral hemisphere", "optionD": "Bilateral peripheral nerves", "correctAnswer": "C" },
    { "question": "Which of the following best illustrates the principle of parsimony (Occam\u2019s razor) in neurological diagnosis?", "optionA": "Always diagnose the most common disease", "optionB": "Assume every symptom represents a separate disease", "optionC": "Prefer a single lesion that explains multiple neurological findings when possible", "optionD": "Ignore symptoms that do not fit the initial diagnosis", "correctAnswer": "C" },
    { "question": "A patient has progressive dysarthria, dysphagia, bilateral extensor plantar responses, and muscle atrophy. Which diagnostic principle is most appropriate?", "optionA": "Assume all findings are unrelated", "optionB": "Consider whether a single multisystem neurological disorder could explain them", "optionC": "Exclude motor neuron disease because it is uncommon", "optionD": "Diagnose a psychiatric disorder first", "correctAnswer": "B" },
    { "question": "Which component of the neurological history is particularly important when evaluating possible seizures?", "optionA": "Hair color", "optionB": "Description provided by an observer or witness", "optionC": "Blood group", "optionD": "Hand dominance alone", "correctAnswer": "B" },
    { "question": "Why is the patient's family history important in neurological diagnosis?", "optionA": "All neurological disorders are inherited", "optionB": "Family history can identify hereditary disorders and may reveal patterns not recognized by the patient", "optionC": "It replaces neurological examination", "optionD": "It determines the treatment in every neurological disorder", "correctAnswer": "B" },
    { "question": "Which of the following is an important component of social history in a neurological patient?", "optionA": "Occupation and potential occupational exposure", "optionB": "Favorite food", "optionC": "Clothing preference", "optionD": "Blood group", "correctAnswer": "A" },
    { "question": "Which finding during neurological examination may suggest parkinsonism?", "optionA": "Hypomimia", "optionB": "Hyperreflexia alone", "optionC": "Isolated sensory loss", "optionD": "Papilledema", "correctAnswer": "A" },
    { "question": "A patient has ptosis and diplopia. The pattern of ocular movements and fatigability would be particularly useful because it may help distinguish:", "optionA": "Myasthenia gravis from other causes of ocular weakness", "optionB": "Migraine from tension headache", "optionC": "Peripheral neuropathy from myelopathy", "optionD": "Parkinson disease from essential tremor", "correctAnswer": "A" },
    { "question": "During examination, a patient develops tremor, dystonia, myoclonus, or chorea. These findings are particularly relevant to assessment of:", "optionA": "Movement disorders", "optionB": "Peripheral vascular disease", "optionC": "Isolated optic neuropathy", "optionD": "Meningitis only", "correctAnswer": "A" },
    { "question": "Which bedside maneuver is specifically useful for assessing postural stability and can help reveal cerebellar or proprioceptive dysfunction?", "optionA": "Romberg test", "optionB": "Babinski test", "optionC": "Snellen test", "optionD": "Weber test", "correctAnswer": "A" },
    { "question": "A patient can walk normally but develops marked instability when asked to perform tandem gait. This finding suggests that:", "optionA": "The screening neurological examination may have missed an important abnormality", "optionB": "The neurological examination is definitely normal", "optionC": "The patient must have a psychiatric disorder", "optionD": "MRI is never required", "correctAnswer": "A" },
    { "question": "Which of the following is listed as a major category of pathophysiological mechanisms of neurological disease?", "optionA": "Infectious", "optionB": "Cosmetic", "optionC": "Behavioral only", "optionD": "Nutritional preference", "correctAnswer": "A" },
    { "question": "After anatomical localization and identification of possible pathophysiological mechanisms, what is the next major purpose of constructing a differential diagnosis?", "optionA": "To identify every disease ever described", "optionB": "To rank possible diseases according to how well they fit the patient's features", "optionC": "To avoid considering uncommon diseases", "optionD": "To replace clinical examination with laboratory testing", "correctAnswer": "B" }
  ]
};
