let questions = [
    {
        "id": "sce001",
        "subject": "Movement Disorders",
        "category": "Movement Disorders",
        "difficulty": "SCE",
        "questionNumber": 1,
        "questionText": "A 68-year-old woman develops parkinsonism with frequent visual hallucinations, marked fluctuations in attention and cognition, and REM sleep behaviour disorder. Her motor symptoms began only 6 months before the cognitive symptoms. What is the most likely diagnosis?",
        "optionA": "Parkinson disease with dementia",
        "optionB": "Dementia with Lewy bodies",
        "optionC": "Progressive supranuclear palsy",
        "optionD": "Corticobasal degeneration",
        "correctAnswer": "B",
        "explanation": "The close temporal relationship between parkinsonism and early fluctuating cognition with recurrent visual hallucinations favours dementia with Lewy bodies."
    },
    {
        "id": "sce002",
        "subject": "Peripheral Neurology",
        "category": "Peripheral Neurology",
        "difficulty": "SCE",
        "questionNumber": 2,
        "questionText": "A 42-year-old man has progressive asymmetric weakness of the hands over 18 months. There is no sensory loss or wasting, reflexes are preserved, and nerve conduction studies demonstrate motor conduction block outside common entrapment sites. Which diagnosis is most likely?",
        "optionA": "Multifocal motor neuropathy",
        "optionB": "Amyotrophic lateral sclerosis",
        "optionC": "Chronic inflammatory demyelinating polyradiculoneuropathy",
        "optionD": "Inclusion body myositis",
        "correctAnswer": "A",
        "explanation": "Progressive asymmetric pure motor weakness with conduction block and preserved sensation is characteristic of multifocal motor neuropathy."
    },
    {
        "id": "sce003",
        "subject": "Neuroanatomy",
        "category": "Neuroanatomy",
        "difficulty": "SCE",
        "questionNumber": 3,
        "questionText": "A patient develops ipsilateral facial pain and temperature loss, contralateral body pain and temperature loss, ipsilateral Horner syndrome and ipsilateral limb ataxia. Where is the lesion most likely located?",
        "optionA": "Dorsolateral medulla",
        "optionB": "Ventral pons",
        "optionC": "Medial midbrain",
        "optionD": "Internal capsule",
        "correctAnswer": "A",
        "explanation": "This combination localises to the dorsolateral medulla, involving the spinal trigeminal pathway, spinothalamic tract, sympathetic fibres and cerebellar connections."
    },
    {
        "id": "sce004",
        "subject": "Cerebrovascular Neurology",
        "category": "Cerebrovascular Neurology",
        "difficulty": "SCE",
        "questionNumber": 4,
        "questionText": "A 58-year-old man develops sudden vertigo, diplopia, dysarthria and left-sided limb ataxia. Examination shows a left Horner syndrome and reduced pain and temperature sensation on the left side of the face with reduced pain and temperature sensation on the right side of the body. Which vascular territory is most likely involved?",
        "optionA": "Anterior inferior cerebellar artery",
        "optionB": "Posterior inferior cerebellar artery",
        "optionC": "Anterior cerebral artery",
        "optionD": "Posterior cerebral artery",
        "correctAnswer": "B",
        "explanation": "The crossed sensory findings with ipsilateral Horner syndrome and ataxia are typical of a lateral medullary syndrome, usually associated with posterior inferior cerebellar artery territory infarction."
    },
    {
        "id": "sce005",
        "subject": "Epilepsy",
        "category": "Epilepsy",
        "difficulty": "SCE",
        "questionNumber": 5,
        "questionText": "A 27-year-old woman has brief episodes of behavioural arrest lasting 10 seconds, occurring many times daily. During attacks she is unresponsive and has eyelid fluttering. EEG demonstrates generalized 3-Hz spike-and-wave activity. Which seizure type is most likely?",
        "optionA": "Typical absence seizure",
        "optionB": "Focal impaired-awareness seizure",
        "optionC": "Myoclonic seizure",
        "optionD": "Atonic seizure",
        "correctAnswer": "A",
        "explanation": "Very brief frequent episodes of impaired awareness with generalized 3-Hz spike-and-wave activity are characteristic of typical absence seizures."
    },
    {
        "id": "sce006",
        "subject": "Headache",
        "category": "Headache",
        "difficulty": "SCE",
        "questionNumber": 6,
        "questionText": "A 31-year-old woman has recurrent unilateral throbbing headaches lasting 8 hours, associated with nausea, photophobia and visual scintillations immediately before the pain. Neurological examination is normal. Which treatment is most appropriate for an acute moderate-to-severe attack?",
        "optionA": "Sumatriptan",
        "optionB": "Propranolol",
        "optionC": "Pizotifen",
        "optionD": "Topiramate",
        "correctAnswer": "A",
        "explanation": "The clinical pattern is migraine with typical visual aura; a triptan such as sumatriptan is an appropriate acute treatment for a moderate-to-severe attack."
    },
    {
        "id": "sce007",
        "subject": "Neuromuscular",
        "category": "Neuromuscular",
        "difficulty": "SCE",
        "questionNumber": 7,
        "questionText": "A 61-year-old man develops progressive difficulty climbing stairs and rising from chairs. Examination shows predominantly proximal lower-limb weakness, normal sensation and a markedly raised creatine kinase. Which investigation is most useful to distinguish an inflammatory myopathy from a motor neuropathy?",
        "optionA": "Nerve conduction studies and EMG",
        "optionB": "CT angiography",
        "optionC": "Lumbar puncture",
        "optionD": "Carotid Doppler ultrasonography",
        "correctAnswer": "A",
        "explanation": "Electrodiagnostic testing can distinguish a myopathic pattern from neurogenic weakness and is useful when the clinical localisation is uncertain."
    },
    {
        "id": "sce008",
        "subject": "Neuro-ophthalmology",
        "category": "Neuro-ophthalmology",
        "difficulty": "SCE",
        "questionNumber": 8,
        "questionText": "A patient has diplopia that is maximal when looking down and to the right. The images are vertically separated and the separation increases when the head is tilted to the left. Which cranial nerve is most likely affected?",
        "optionA": "Right oculomotor nerve",
        "optionB": "Right trochlear nerve",
        "optionC": "Left trochlear nerve",
        "optionD": "Right abducens nerve",
        "correctAnswer": "B",
        "explanation": "A right trochlear nerve palsy causes vertical diplopia that is worse in downgaze and with left head tilt."
    },
    {
        "id": "sce009",
        "subject": "Multiple Sclerosis",
        "category": "Multiple Sclerosis",
        "difficulty": "SCE",
        "questionNumber": 9,
        "questionText": "A 29-year-old woman has two episodes of neurological dysfunction separated by 10 months: first optic neuritis and later a sensory disturbance affecting the right leg. MRI demonstrates lesions in characteristic periventricular and juxtacortical locations. Which feature most strongly supports multiple sclerosis?",
        "optionA": "Neurological episodes separated in time and affecting different CNS sites",
        "optionB": "A single persistent lesion confined to one peripheral nerve",
        "optionC": "Isolated elevation of serum creatine kinase",
        "optionD": "Normal neurological examination between all symptoms",
        "correctAnswer": "A",
        "explanation": "Multiple sclerosis is supported by dissemination of lesions in time and space, illustrated by separate neurological episodes with characteristic CNS lesions."
    },
    {
        "id": "sce010",
        "subject": "Neuroinfectious Disease",
        "category": "Neuroinfectious Disease",
        "difficulty": "SCE",
        "questionNumber": 10,
        "questionText": "A 45-year-old man presents with fever, headache and neck stiffness. CSF shows markedly raised protein, low glucose, neutrophil predominance and Gram-positive diplococci. Which organism is most likely responsible?",
        "optionA": "Streptococcus pneumoniae",
        "optionB": "Neisseria meningitidis",
        "optionC": "Listeria monocytogenes",
        "optionD": "Haemophilus influenzae",
        "correctAnswer": "A",
        "explanation": "Gram-positive diplococci in a neutrophilic bacterial meningitis pattern strongly support Streptococcus pneumoniae."
    },
    {
        "id": "sce011",
        "subject": "Neuroimmunology",
        "category": "Neuroimmunology",
        "difficulty": "SCE",
        "questionNumber": 11,
        "questionText": "A 35-year-old woman develops bilateral optic neuritis followed a year later by severe paraparesis and bladder dysfunction. MRI shows a longitudinally extensive spinal cord lesion. Which diagnosis should be considered most strongly?",
        "optionA": "Neuromyelitis optica spectrum disorder",
        "optionB": "Typical migraine with aura",
        "optionC": "Peripheral neuropathy",
        "optionD": "Huntington disease",
        "correctAnswer": "A",
        "explanation": "Optic neuritis followed by longitudinally extensive myelitis is a classic pattern raising strong suspicion for neuromyelitis optica spectrum disorder."
    },
    {
        "id": "sce012",
        "subject": "Sleep Neurology",
        "category": "Sleep Neurology",
        "difficulty": "SCE",
        "questionNumber": 12,
        "questionText": "A 57-year-old man repeatedly punches and kicks during vivid dreams. His spouse reports that the movements occur during the latter part of the night. Which sleep disorder is most likely?",
        "optionA": "REM sleep behaviour disorder",
        "optionB": "Periodic limb movement disorder",
        "optionC": "Somnambulism",
        "optionD": "Obstructive sleep apnoea",
        "correctAnswer": "A",
        "explanation": "Complex motor behaviours associated with dream enactment during REM sleep are characteristic of REM sleep behaviour disorder."
    },
    {
        "id": "sce013",
        "subject": "Neuroanatomy",
        "category": "Neuroanatomy",
        "difficulty": "SCE",
        "questionNumber": 13,
        "questionText": "A patient has weakness and impaired proprioception on the right side of the body below the neck, with a left-sided loss of pain and temperature sensation beginning several segments below the lesion. Where is the lesion most likely?",
        "optionA": "Right hemicord of the cervical or upper thoracic spinal cord",
        "optionB": "Left cerebral hemisphere",
        "optionC": "Right peripheral nerve",
        "optionD": "Bilateral dorsal columns of the brainstem",
        "correctAnswer": "A",
        "explanation": "Ipsilateral corticospinal and dorsal-column deficits with contralateral spinothalamic loss are characteristic of a spinal cord hemisection pattern."
    },
    {
        "id": "sce014",
        "subject": "Neuromuscular",
        "category": "Neuromuscular",
        "difficulty": "SCE",
        "questionNumber": 14,
        "questionText": "A 72-year-old man develops slowly progressive asymmetric weakness of finger flexion and grip. Examination shows wasting of the forearms and marked weakness of distal finger flexion. Sensation is preserved. Which muscle is chiefly responsible for flexion of the distal interphalangeal joints?",
        "optionA": "Flexor digitorum profundus",
        "optionB": "Flexor digitorum superficialis",
        "optionC": "Flexor carpi radialis",
        "optionD": "Flexor pollicis brevis",
        "correctAnswer": "A",
        "explanation": "Flexor digitorum profundus is the principal muscle producing flexion at the distal interphalangeal joints."
    },
    {
        "id": "sce015",
        "subject": "Movement Disorders",
        "category": "Movement Disorders",
        "difficulty": "SCE",
        "questionNumber": 15,
        "questionText": "A 66-year-old man has progressive parkinsonism with early unexplained falls, axial rigidity and impaired vertical saccades. There is little improvement with an adequate trial of levodopa. Which diagnosis is most likely?",
        "optionA": "Progressive supranuclear palsy",
        "optionB": "Idiopathic Parkinson disease",
        "optionC": "Essential tremor",
        "optionD": "Huntington disease",
        "correctAnswer": "A",
        "explanation": "Early falls, axial-predominant parkinsonism, vertical saccadic impairment and poor levodopa response strongly suggest progressive supranuclear palsy."
    },
    {
        "id": "sce016",
        "subject": "Cerebrovascular Neurology",
        "category": "Cerebrovascular Neurology",
        "difficulty": "SCE",
        "questionNumber": 16,
        "questionText": "A 74-year-old woman suddenly develops aphasia and weakness of the right face and arm, with relative sparing of the leg. Which arterial territory is most likely affected?",
        "optionA": "Left middle cerebral artery",
        "optionB": "Left anterior cerebral artery",
        "optionC": "Right posterior cerebral artery",
        "optionD": "Basilar artery",
        "correctAnswer": "A",
        "explanation": "Aphasia with predominant contralateral face and arm weakness localises to the dominant hemisphere middle cerebral artery territory."
    },
    {
        "id": "sce017",
        "subject": "Epilepsy",
        "category": "Epilepsy",
        "difficulty": "SCE",
        "questionNumber": 17,
        "questionText": "A 34-year-old man has recurrent episodes beginning with an unpleasant rising epigastric sensation followed by behavioural arrest and lip smacking. He is confused for several minutes afterward. Where is the seizure most likely to originate?",
        "optionA": "Temporal lobe",
        "optionB": "Occipital lobe",
        "optionC": "Primary motor cortex",
        "optionD": "Cerebellum",
        "correctAnswer": "A",
        "explanation": "An epigastric rising sensation, automatisms and postictal confusion are characteristic features of focal seizures arising from the temporal lobe."
    },
    {
        "id": "sce018",
        "subject": "Peripheral Neurology",
        "category": "Peripheral Neurology",
        "difficulty": "SCE",
        "questionNumber": 18,
        "questionText": "A woman develops foot drop after prolonged labour. Examination shows weakness of ankle dorsiflexion and eversion with sensory loss over the dorsum of the foot and lateral lower leg. Knee and ankle reflexes are preserved. Which lesion is most likely?",
        "optionA": "Common peroneal neuropathy",
        "optionB": "S1 radiculopathy",
        "optionC": "Femoral neuropathy",
        "optionD": "Tibial neuropathy",
        "correctAnswer": "A",
        "explanation": "Weakness of dorsiflexion and eversion with sensory loss over the dorsum of the foot and lateral lower leg is compatible with common peroneal neuropathy."
    },
    {
        "id": "sce019",
        "subject": "Neuro-ophthalmology",
        "category": "Neuro-ophthalmology",
        "difficulty": "SCE",
        "questionNumber": 19,
        "questionText": "A patient has impaired abduction of the right eye. The right pupil is normal and there is no ptosis. Which cranial nerve is most likely affected?",
        "optionA": "Right abducens nerve",
        "optionB": "Right oculomotor nerve",
        "optionC": "Right trochlear nerve",
        "optionD": "Right optic nerve",
        "correctAnswer": "A",
        "explanation": "The abducens nerve supplies lateral rectus, so an isolated lesion produces impaired abduction without the pupil findings expected from an oculomotor lesion."
    },
    {
        "id": "sce020",
        "subject": "Cognitive Neurology",
        "category": "Cognitive Neurology",
        "difficulty": "SCE",
        "questionNumber": 20,
        "questionText": "A 69-year-old man develops progressive memory impairment accompanied by prominent visuospatial difficulties, fluctuating attention and recurrent well-formed visual hallucinations. Which diagnosis is most likely?",
        "optionA": "Dementia with Lewy bodies",
        "optionB": "Frontotemporal dementia",
        "optionC": "Vascular dementia",
        "optionD": "Normal-pressure hydrocephalus",
        "correctAnswer": "A",
        "explanation": "Fluctuating cognition, recurrent well-formed visual hallucinations and visuospatial impairment are characteristic features of dementia with Lewy bodies."
    },
    {
        "id": "sce021",
        "subject": "Spinal Neurology",
        "category": "Spinal Neurology",
        "difficulty": "SCE",
        "questionNumber": 21,
        "questionText": "A patient develops bilateral leg weakness, a sensory level and urinary retention. MRI demonstrates an acute compressive lesion of the thoracic spinal cord. Which clinical finding would most strongly indicate an upper motor neuron process below the lesion?",
        "optionA": "Extensor plantar responses",
        "optionB": "Fasciculations",
        "optionC": "Marked distal muscle wasting at onset",
        "optionD": "Absent abdominal reflexes alone",
        "correctAnswer": "A",
        "explanation": "An extensor plantar response is a characteristic sign of corticospinal tract dysfunction and supports an upper motor neuron process."
    },
    {
        "id": "sce022",
        "subject": "Neuromuscular",
        "category": "Neuromuscular",
        "difficulty": "SCE",
        "questionNumber": 22,
        "questionText": "A 48-year-old woman develops fluctuating ptosis and diplopia that worsen toward evening. Limb power is normal and sensation is intact. Which investigation is most directly useful for confirming the suspected diagnosis?",
        "optionA": "Acetylcholine receptor antibody testing",
        "optionB": "Serum creatine kinase alone",
        "optionC": "CSF oligoclonal bands",
        "optionD": "Serum ACE concentration",
        "correctAnswer": "A",
        "explanation": "Fluctuating ocular weakness with fatigability strongly suggests myasthenia gravis, for which acetylcholine receptor antibody testing is a direct diagnostic investigation."
    },
    {
        "id": "sce023",
        "subject": "Headache",
        "category": "Headache",
        "difficulty": "SCE",
        "questionNumber": 23,
        "questionText": "A 42-year-old man develops repeated attacks of excruciating unilateral orbital pain lasting about 90 minutes. The attacks occur at night and are associated with ipsilateral lacrimation and nasal congestion. Which acute treatment is most appropriate?",
        "optionA": "High-flow oxygen",
        "optionB": "Oral propranolol",
        "optionC": "Daily aspirin",
        "optionD": "Oral prednisolone as sole acute treatment",
        "correctAnswer": "A",
        "explanation": "The pattern is typical of cluster headache; high-flow oxygen is an established rapid acute treatment."
    },
    {
        "id": "sce024",
        "subject": "Neuroinfectious Disease",
        "category": "Neuroinfectious Disease",
        "difficulty": "SCE",
        "questionNumber": 24,
        "questionText": "A patient with chronic headache and confusion has CSF lymphocytosis, markedly raised protein, low glucose and a negative Gram stain. Brain imaging shows hydrocephalus. Which diagnosis should be considered strongly?",
        "optionA": "Tuberculous meningitis",
        "optionB": "Typical bacterial meningitis caused by pneumococcus",
        "optionC": "Guillain–Barré syndrome",
        "optionD": "Migraine with aura",
        "correctAnswer": "A",
        "explanation": "Subacute meningitic illness with lymphocytic CSF, low glucose, high protein and hydrocephalus is strongly suggestive of tuberculous meningitis."
    },
    {
        "id": "sce025",
        "subject": "Cerebellar Neurology",
        "category": "Cerebellar Neurology",
        "difficulty": "SCE",
        "questionNumber": 25,
        "questionText": "A 76-year-old man develops gait ataxia shortly after a prolonged intensive-care admission during which he received gentamicin, with documented toxic drug concentrations. Head-thrust testing is normal. Which diagnosis is most likely?",
        "optionA": "Gentamicin-related vestibular toxicity",
        "optionB": "Acute alcohol withdrawal",
        "optionC": "Peripheral facial neuropathy",
        "optionD": "Cervical myelopathy",
        "correctAnswer": "A",
        "explanation": "A history of toxic gentamicin exposure with subsequent imbalance raises concern for gentamicin-related vestibular toxicity."
    },
    {
        "id": "sce026",
        "subject": "Neuroimmunology",
        "category": "Neuroimmunology",
        "difficulty": "SCE",
        "questionNumber": 26,
        "questionText": "A 30-year-old woman has recurrent neurological episodes with optic neuritis and a longitudinally extensive spinal cord lesion. Oligoclonal bands are absent and aquaporin-4 antibodies are negative. Which additional antibody is particularly relevant in this clinical setting?",
        "optionA": "Myelin oligodendrocyte glycoprotein antibody",
        "optionB": "Acetylcholine receptor antibody",
        "optionC": "Voltage-gated calcium channel antibody",
        "optionD": "Anti-dsDNA antibody",
        "correctAnswer": "A",
        "explanation": "MOG antibody-associated disease is an important differential in optic neuritis and longitudinally extensive myelitis, particularly when aquaporin-4 antibodies are negative."
    },
    {
        "id": "sce027",
        "subject": "Cerebrovascular Neurology",
        "category": "Cerebrovascular Neurology",
        "difficulty": "SCE",
        "questionNumber": 27,
        "questionText": "A 63-year-old man develops sudden pure weakness of the face, arm and leg on the right without aphasia, visual field loss or sensory symptoms. Which lesion is most likely?",
        "optionA": "Left internal capsule lacunar infarct",
        "optionB": "Right occipital infarct",
        "optionC": "Left cerebellar infarct",
        "optionD": "Right temporal lobe infarct",
        "correctAnswer": "A",
        "explanation": "A pure motor hemiparesis without cortical signs is characteristic of a lacunar infarct involving corticospinal fibres, commonly in the internal capsule."
    },
    {
        "id": "sce028",
        "subject": "Epilepsy",
        "category": "Epilepsy",
        "difficulty": "SCE",
        "questionNumber": 28,
        "questionText": "A 23-year-old man has a generalized tonic-clonic seizure immediately after a mild head injury, with recovery of consciousness within 30 seconds and no postictal confusion. Neurological examination is normal. Which investigation is most appropriate in this uncomplicated presentation?",
        "optionA": "No routine neurological investigation",
        "optionB": "Serum prolactin",
        "optionC": "Routine EEG solely because of the brief convulsive movements",
        "optionD": "Skull radiography",
        "correctAnswer": "A",
        "explanation": "Brief convulsive movements can accompany uncomplicated concussion; in an otherwise neurologically normal patient without features suggesting epilepsy, routine neurological investigation is not necessarily indicated."
    },
    {
        "id": "sce029",
        "subject": "Sleep Neurology",
        "category": "Sleep Neurology",
        "difficulty": "SCE",
        "questionNumber": 29,
        "questionText": "A 50-year-old obese man has excessive daytime sleepiness and breathlessness when supine. His forced vital capacity falls from 3.0 L sitting to 1.2 L when semi-recumbent. Which mechanism best explains the positional respiratory deterioration?",
        "optionA": "Inspiratory muscle weakness",
        "optionB": "An isolated anxiety disorder",
        "optionC": "Primary laryngeal obstruction",
        "optionD": "Peripheral sensory neuropathy",
        "correctAnswer": "A",
        "explanation": "A large positional fall in vital capacity suggests significant respiratory muscle weakness, particularly impaired inspiratory function when supine."
    },
    {
        "id": "sce030",
        "subject": "Peripheral Neurology",
        "category": "Peripheral Neurology",
        "difficulty": "SCE",
        "questionNumber": 30,
        "questionText": "A patient has weakness of knee flexion, ankle dorsiflexion and plantar flexion, with sensory loss involving the dorsum and sole of the foot. Which lesion best accounts for involvement of multiple divisions of the lower limb with this distribution?",
        "optionA": "Sciatic nerve lesion",
        "optionB": "Common peroneal nerve lesion",
        "optionC": "Isolated L5 root lesion",
        "optionD": "Isolated tibial nerve lesion",
        "correctAnswer": "A",
        "explanation": "Weakness involving muscles supplied by both tibial and common peroneal divisions with widespread foot sensory loss is most consistent with a sciatic nerve lesion."
    },
    {
        "id": "sce031",
        "subject": "Neuro-ophthalmology",
        "category": "Neuro-ophthalmology",
        "difficulty": "SCE",
        "questionNumber": 31,
        "questionText": "A patient has bilateral optic neuritis with subsequent paraparesis and bladder dysfunction. MRI of the brain is normal but MRI of the spinal cord shows a continuous lesion extending across several vertebral segments. Which feature most strongly argues against typical multiple sclerosis?",
        "optionA": "Longitudinally extensive spinal cord involvement",
        "optionB": "Optic neuritis",
        "optionC": "Urinary symptoms",
        "optionD": "A sensory disturbance",
        "correctAnswer": "A",
        "explanation": "A longitudinally extensive spinal cord lesion is atypical for classic multiple sclerosis and should prompt consideration of alternative inflammatory disorders such as NMOSD or MOG-associated disease."
    },
    {
        "id": "sce032",
        "subject": "Movement Disorders",
        "category": "Movement Disorders",
        "difficulty": "SCE",
        "questionNumber": 32,
        "questionText": "A 64-year-old woman develops asymmetric limb rigidity, apraxia of the affected hand and cortical sensory impairment. She has difficulty making learned purposeful movements despite preserved basic strength. Which diagnosis is most likely?",
        "optionA": "Corticobasal syndrome",
        "optionB": "Essential tremor",
        "optionC": "Typical Parkinson disease",
        "optionD": "Huntington disease",
        "correctAnswer": "A",
        "explanation": "Asymmetric parkinsonism accompanied by apraxia and cortical sensory dysfunction is characteristic of corticobasal syndrome."
    },
    {
        "id": "sce033",
        "subject": "Cognitive Neurology",
        "category": "Cognitive Neurology",
        "difficulty": "SCE",
        "questionNumber": 33,
        "questionText": "A 58-year-old man develops progressive behavioural disinhibition, loss of empathy and stereotyped behaviour. Memory is relatively preserved early in the illness. Which diagnosis is most likely?",
        "optionA": "Behavioural-variant frontotemporal dementia",
        "optionB": "Dementia with Lewy bodies",
        "optionC": "Typical Alzheimer disease",
        "optionD": "Normal-pressure hydrocephalus",
        "correctAnswer": "A",
        "explanation": "Early behavioural disinhibition, loss of empathy and stereotyped behaviour with relative early memory preservation favour behavioural-variant frontotemporal dementia."
    },
    {
        "id": "sce034",
        "subject": "Spinal Neurology",
        "category": "Spinal Neurology",
        "difficulty": "SCE",
        "questionNumber": 34,
        "questionText": "A 55-year-old man has progressive hand weakness and wasting followed by stiffness and weakness of both legs. Sensory examination is initially normal. MRI demonstrates cervical spinal cord compression. Which diagnosis best explains the combination?",
        "optionA": "Cervical cord compression causing segmental lower motor neuron signs with myelopathy",
        "optionB": "Isolated common peroneal neuropathy",
        "optionC": "Guillain–Barré syndrome",
        "optionD": "Pure cerebellar degeneration",
        "correctAnswer": "A",
        "explanation": "Cervical cord compression can produce lower motor neuron signs at the level of the lesion in the hands together with upper motor neuron signs in the legs."
    },
    {
        "id": "sce035",
        "subject": "Neuroinfectious Disease",
        "category": "Neuroinfectious Disease",
        "difficulty": "SCE",
        "questionNumber": 35,
        "questionText": "A severely immunocompromised patient develops subacute headache, confusion and cranial nerve abnormalities. CSF shows lymphocytosis, raised protein and low glucose. Which additional test would be particularly useful when cryptococcal meningitis is suspected?",
        "optionA": "Cryptococcal antigen testing",
        "optionB": "Serum creatine kinase",
        "optionC": "Acetylcholine receptor antibodies",
        "optionD": "Carotid Doppler ultrasonography",
        "correctAnswer": "A",
        "explanation": "Cryptococcal antigen testing is a key diagnostic investigation when cryptococcal meningitis is suspected, particularly in an immunocompromised patient."
    },
    {
        "id": "sce036",
        "subject": "Neuromuscular",
        "category": "Neuromuscular",
        "difficulty": "SCE",
        "questionNumber": 36,
        "questionText": "A 39-year-old woman has progressive weakness of the hands over 2 years. There is no sensory loss, the cervical MRI is normal and creatine kinase is only mildly elevated. Which finding would most strongly favour multifocal motor neuropathy over a primary muscle disorder?",
        "optionA": "Motor conduction block with preserved sensory responses",
        "optionB": "Myopathic motor units on EMG",
        "optionC": "Marked proximal weakness with high creatine kinase",
        "optionD": "Inflammatory changes on muscle biopsy",
        "correctAnswer": "A",
        "explanation": "Motor conduction block with preserved sensory responses is a characteristic electrodiagnostic pattern supporting multifocal motor neuropathy."
    },
    {
        "id": "sce037",
        "subject": "Cerebrovascular Neurology",
        "category": "Cerebrovascular Neurology",
        "difficulty": "SCE",
        "questionNumber": 37,
        "questionText": "A 50-year-old man has a transient episode of diplopia and contralateral hemisensory loss. Examination during the episode shows ipsilateral partial ptosis and a smaller pupil, with preserved extraocular movements. Which anatomical region is most likely involved?",
        "optionA": "Lateral midbrain",
        "optionB": "Ventral pons",
        "optionC": "Dorsolateral medulla",
        "optionD": "Primary visual cortex",
        "correctAnswer": "A",
        "explanation": "Ipsilateral partial Horner syndrome combined with crossed sensory findings and ocular symptoms can localise to the lateral midbrain in the described pattern."
    },
    {
        "id": "sce038",
        "subject": "Headache",
        "category": "Headache",
        "difficulty": "SCE",
        "questionNumber": 38,
        "questionText": "A 40-year-old woman has three attacks of unilateral headache over 7 months. Each lasts about 12 hours, is preceded by visual aura and is associated with nausea. Neurological examination is normal. Which treatment is most appropriate at the onset of a typical severe attack?",
        "optionA": "A triptan",
        "optionB": "Long-term propranolol started solely for these three attacks",
        "optionC": "Daily furosemide",
        "optionD": "Immediate lumbar puncture",
        "correctAnswer": "A",
        "explanation": "The pattern is consistent with migraine with aura, and a triptan is an appropriate acute treatment for a severe attack."
    },
    {
        "id": "sce039",
        "subject": "Neuroanatomy",
        "category": "Neuroanatomy",
        "difficulty": "SCE",
        "questionNumber": 39,
        "questionText": "A patient develops weakness of the right arm and leg with increased tone and an extensor plantar response. There is no cortical sensory deficit, aphasia or visual field defect. Which anatomical site is most likely to produce this pattern?",
        "optionA": "Left internal capsule",
        "optionB": "Right occipital cortex",
        "optionC": "Left cerebellar hemisphere",
        "optionD": "Right temporal cortex",
        "correctAnswer": "A",
        "explanation": "A dense contralateral upper motor neuron pattern without cortical signs is typical of a lesion affecting compact corticospinal fibres in the internal capsule."
    },
    {
        "id": "sce040",
        "subject": "Neuro-ophthalmology",
        "category": "Neuro-ophthalmology",
        "difficulty": "SCE",
        "questionNumber": 40,
        "questionText": "A patient with raised intracranial pressure develops progressive visual field loss despite weight reduction, acetazolamide and repeated therapeutic lumbar puncture. What is the most appropriate principle of management?",
        "optionA": "Urgent definitive treatment to protect vision",
        "optionB": "Continue observation until visual acuity is completely lost",
        "optionC": "Perform daily lumbar punctures indefinitely as sole therapy",
        "optionD": "Stop all treatment because papilloedema is expected",
        "correctAnswer": "A",
        "explanation": "Progressive visual deterioration despite medical and temporary pressure-lowering measures represents a vision-threatening situation requiring urgent definitive intervention."
    },
{
        "id": "easy041",
        "subject": "Cerebrovascular Neurology",
        "category": "Cerebrovascular Neurology",
        "difficulty": "Easy",
        "questionNumber": 41,
        "questionText": "A 72-year-old man suddenly develops weakness of the right face and arm with expressive aphasia. Which cerebral hemisphere is most likely affected?",
        "optionA": "Right hemisphere",
        "optionB": "Left hemisphere",
        "optionC": "Cerebellum",
        "optionD": "Brainstem only",
        "correctAnswer": "B",
        "explanation": "Expressive aphasia with right-sided face and arm weakness localises to the dominant left cerebral hemisphere, typically involving the left frontal language and motor regions."
    },
    {
        "id": "easy042",
        "subject": "Epilepsy",
        "category": "Epilepsy",
        "difficulty": "Easy",
        "questionNumber": 42,
        "questionText": "Which feature most strongly suggests a focal onset seizure rather than a typical generalized absence seizure?",
        "optionA": "Brief staring with immediate recovery",
        "optionB": "3-Hz generalized spike-and-wave activity",
        "optionC": "An aura followed by impaired awareness",
        "optionD": "Episodes provoked by hyperventilation",
        "correctAnswer": "C",
        "explanation": "Auras are subjective focal symptoms produced by focal cortical activity and strongly support focal seizure onset."
    },
    {
        "id": "easy043",
        "subject": "Movement Disorders",
        "category": "Movement Disorders",
        "difficulty": "Easy",
        "questionNumber": 43,
        "questionText": "Which clinical feature is a core motor feature of Parkinson disease?",
        "optionA": "Bradykinesia",
        "optionB": "Flaccid paralysis",
        "optionC": "Sensory ataxia",
        "optionD": "Myoclonus as the defining feature",
        "correctAnswer": "A",
        "explanation": "Bradykinesia is essential to the clinical diagnosis of parkinsonism and is typically accompanied by rigidity, rest tremor or both."
    },
    {
        "id": "easy044",
        "subject": "Headache",
        "category": "Headache",
        "difficulty": "Easy",
        "questionNumber": 44,
        "questionText": "Which headache feature is most characteristic of migraine?",
        "optionA": "Bilateral mild pressure without associated symptoms",
        "optionB": "Unilateral pulsating pain with nausea and activity aggravation",
        "optionC": "Sudden maximal pain within seconds in every attack",
        "optionD": "Pain only when standing upright",
        "correctAnswer": "B",
        "explanation": "Migraine commonly causes unilateral, pulsating moderate-to-severe headache with nausea and/or photophobia or phonophobia, often worsened by routine activity."
    },
    {
        "id": "easy045",
        "subject": "Neuromuscular",
        "category": "Neuromuscular",
        "difficulty": "Easy",
        "questionNumber": 45,
        "questionText": "A patient has fatigable ptosis and diplopia that worsen late in the day. Which disorder is most likely?",
        "optionA": "Myasthenia gravis",
        "optionB": "Parkinson disease",
        "optionC": "Multiple sclerosis only affecting sensation",
        "optionD": "Essential tremor",
        "correctAnswer": "A",
        "explanation": "Fluctuating, fatigable ocular weakness with ptosis and diplopia is characteristic of myasthenia gravis."
    },
    {
        "id": "easy046",
        "subject": "Peripheral Neurology",
        "category": "Peripheral Neurology",
        "difficulty": "Easy",
        "questionNumber": 46,
        "questionText": "Which pattern is most typical of a length-dependent peripheral polyneuropathy?",
        "optionA": "Sensory symptoms beginning in the feet and progressing proximally",
        "optionB": "Sudden isolated facial weakness",
        "optionC": "Purely proximal weakness with preserved sensation",
        "optionD": "Hemianopia with aphasia",
        "correctAnswer": "A",
        "explanation": "Length-dependent polyneuropathies usually begin distally, most often in the feet, producing a stocking distribution before symptoms progress proximally."
    },
    {
        "id": "easy047",
        "subject": "Multiple Sclerosis",
        "category": "Multiple Sclerosis",
        "difficulty": "Easy",
        "questionNumber": 47,
        "questionText": "Which symptom is particularly typical of optic neuritis associated with multiple sclerosis?",
        "optionA": "Pain with eye movement and reduced visual acuity",
        "optionB": "Complete bilateral blindness from birth",
        "optionC": "Isolated hearing loss",
        "optionD": "Transient loss of smell only",
        "correctAnswer": "A",
        "explanation": "Typical optic neuritis causes subacute monocular visual loss, often accompanied by periocular pain that worsens with eye movement."
    },
    {
        "id": "easy048",
        "subject": "Neuroinfectious Disease",
        "category": "Neuroinfectious Disease",
        "difficulty": "Easy",
        "questionNumber": 48,
        "questionText": "Which CSF pattern is most typical of acute bacterial meningitis?",
        "optionA": "Neutrophilic pleocytosis, high protein and low glucose",
        "optionB": "No cells with very low protein",
        "optionC": "Lymphocytes with normal protein and high glucose",
        "optionD": "Isolated red blood cells without other abnormalities",
        "correctAnswer": "A",
        "explanation": "Acute bacterial meningitis classically produces a neutrophil-predominant CSF pleocytosis, elevated protein and reduced CSF glucose."
    },
    {
        "id": "easy049",
        "subject": "Neuro-ophthalmology",
        "category": "Neuro-ophthalmology",
        "difficulty": "Easy",
        "questionNumber": 49,
        "questionText": "A patient has a homonymous hemianopia. What does this finding indicate?",
        "optionA": "A lesion anterior to the optic chiasm",
        "optionB": "A lesion involving the post-chiasmal visual pathway",
        "optionC": "A lesion confined to the retina of one eye",
        "optionD": "A lesion of the optic nerve head only",
        "correctAnswer": "B",
        "explanation": "Homonymous visual field loss affects the same side of the visual field in both eyes and localises posterior to the optic chiasm."
    },
    {
        "id": "easy050",
        "subject": "Cognitive Neurology",
        "category": "Cognitive Neurology",
        "difficulty": "Easy",
        "questionNumber": 50,
        "questionText": "Which cognitive domain is primarily affected when a patient cannot form new long-term memories despite otherwise preserved attention?",
        "optionA": "Episodic memory",
        "optionB": "Visual acuity",
        "optionC": "Motor coordination",
        "optionD": "Auditory reflexes",
        "correctAnswer": "A",
        "explanation": "Episodic memory refers to memory for personally experienced events and is especially vulnerable to dysfunction of medial temporal memory structures."
    },
    {
        "id": "moderate051",
        "subject": "Cerebrovascular Neurology",
        "category": "Cerebrovascular Neurology",
        "difficulty": "Moderate",
        "questionNumber": 51,
        "questionText": "A patient develops sudden pure motor weakness of the right face, arm and leg without aphasia, neglect or visual field loss. Which lesion is most likely?",
        "optionA": "Left posterior limb of the internal capsule",
        "optionB": "Right occipital cortex",
        "optionC": "Left cerebellar hemisphere",
        "optionD": "Right temporal cortex",
        "correctAnswer": "A",
        "explanation": "A pure contralateral motor syndrome without cortical signs is typical of a lacunar infarct involving the posterior limb of the internal capsule, where corticospinal fibres are densely packed."
    },
    {
        "id": "moderate052",
        "subject": "Epilepsy",
        "category": "Epilepsy",
        "difficulty": "Moderate",
        "questionNumber": 52,
        "questionText": "A 19-year-old has brief episodes of staring and unresponsiveness several times daily, with immediate recovery and no postictal confusion. EEG shows generalized 3-Hz spike-and-wave discharges. What is the most likely seizure type?",
        "optionA": "Focal impaired-awareness seizure",
        "optionB": "Typical absence seizure",
        "optionC": "Focal aware seizure",
        "optionD": "Atonic seizure",
        "correctAnswer": "B",
        "explanation": "Typical absence seizures present with brief behavioral arrest, rapid recovery and generalized approximately 3-Hz spike-and-wave discharges, often occurring many times per day."
    },
    {
        "id": "moderate053",
        "subject": "Movement Disorders",
        "category": "Movement Disorders",
        "difficulty": "Moderate",
        "questionNumber": 53,
        "questionText": "A patient with parkinsonism develops early frequent falls, vertical gaze limitation and axial rigidity within the first few years. Which diagnosis should be considered most strongly?",
        "optionA": "Progressive supranuclear palsy",
        "optionB": "Essential tremor",
        "optionC": "Huntington disease",
        "optionD": "Hemifacial spasm",
        "correctAnswer": "A",
        "explanation": "Early postural instability with falls, axial rigidity and vertical supranuclear gaze palsy are characteristic clues to progressive supranuclear palsy."
    },
    {
        "id": "moderate054",
        "subject": "Headache",
        "category": "Headache",
        "difficulty": "Moderate",
        "questionNumber": 54,
        "questionText": "A 30-year-old woman has recurrent unilateral pulsating headaches lasting 8–12 hours with nausea and photophobia. Examination is normal between attacks. Which feature would be a red flag requiring evaluation for a secondary headache disorder?",
        "optionA": "Similar attacks for several years",
        "optionB": "Headache triggered by cough with abrupt onset",
        "optionC": "Photophobia during attacks",
        "optionD": "Nausea during attacks",
        "correctAnswer": "B",
        "explanation": "A new headache precipitated by coughing or straining, especially with abrupt onset, is a red flag for a structural or pressure-related secondary headache and warrants appropriate evaluation."
    },
    {
        "id": "moderate055",
        "subject": "Neuromuscular",
        "category": "Neuromuscular",
        "difficulty": "Moderate",
        "questionNumber": 55,
        "questionText": "A patient has proximal limb weakness, dysphagia and a markedly elevated creatine kinase. Which finding would most strongly support an inflammatory myopathy rather than a neuromuscular junction disorder?",
        "optionA": "Fatigability with normal CK",
        "optionB": "Sensory loss in a stocking distribution",
        "optionC": "Myopathic EMG changes with elevated CK",
        "optionD": "Fluctuating ptosis alone",
        "correctAnswer": "C",
        "explanation": "Inflammatory myopathies cause primary muscle injury, often producing substantial CK elevation and myopathic EMG findings; neuromuscular junction disorders generally do not markedly elevate CK."
    },
    {
        "id": "moderate056",
        "subject": "Peripheral Neurology",
        "category": "Peripheral Neurology",
        "difficulty": "Moderate",
        "questionNumber": 56,
        "questionText": "A patient develops progressive ascending weakness and areflexia one week after a diarrheal illness. Which finding would most support Guillain–Barré syndrome?",
        "optionA": "CSF albuminocytologic dissociation",
        "optionB": "Marked CSF neutrophilia with low glucose",
        "optionC": "A focal cortical lesion on MRI",
        "optionD": "Isolated sensory level on the trunk",
        "correctAnswer": "A",
        "explanation": "Guillain–Barré syndrome commonly shows albuminocytologic dissociation, meaning elevated CSF protein with a normal or only minimally elevated cell count, although this may be absent early."
    },
    {
        "id": "moderate057",
        "subject": "Multiple Sclerosis",
        "category": "Multiple Sclerosis",
        "difficulty": "Moderate",
        "questionNumber": 57,
        "questionText": "A patient has episodes of neurological dysfunction separated by months, affecting optic nerve and spinal cord at different times. Which principle is central to diagnosing multiple sclerosis?",
        "optionA": "Evidence of dissemination in space and time",
        "optionB": "Persistent isolated peripheral neuropathy",
        "optionC": "A single nonspecific headache",
        "optionD": "Only the presence of elevated CK",
        "correctAnswer": "A",
        "explanation": "Multiple sclerosis requires evidence supporting dissemination of lesions in the central nervous system in space and time, interpreted using the appropriate diagnostic criteria and exclusion of better explanations."
    },
    {
        "id": "moderate058",
        "subject": "Neuroinfectious Disease",
        "category": "Neuroinfectious Disease",
        "difficulty": "Moderate",
        "questionNumber": 58,
        "questionText": "An immunocompromised patient develops subacute headache, fever and multiple ring-enhancing brain lesions. Which diagnosis should be strongly considered when the lesions are in the basal ganglia?",
        "optionA": "Cerebral toxoplasmosis",
        "optionB": "Typical migraine",
        "optionC": "Parkinson disease",
        "optionD": "Idiopathic peripheral neuropathy",
        "correctAnswer": "A",
        "explanation": "In an immunocompromised patient, especially with advanced HIV infection, multiple ring-enhancing lesions involving the basal ganglia are a classic presentation of cerebral toxoplasmosis, although other diagnoses such as primary CNS lymphoma may need consideration."
    },
    {
        "id": "moderate059",
        "subject": "Neuro-ophthalmology",
        "category": "Neuro-ophthalmology",
        "difficulty": "Moderate",
        "questionNumber": 59,
        "questionText": "A patient has ptosis, a dilated poorly reactive pupil and the eye positioned down and out. Which cranial nerve lesion best explains the findings?",
        "optionA": "Optic nerve",
        "optionB": "Oculomotor nerve",
        "optionC": "Abducens nerve",
        "optionD": "Trochlear nerve",
        "correctAnswer": "B",
        "explanation": "A complete oculomotor nerve palsy causes ptosis and impaired most extraocular movements, leaving the eye down and out; parasympathetic involvement may produce a dilated pupil."
    },
    {
        "id": "moderate060",
        "subject": "Cognitive Neurology",
        "category": "Cognitive Neurology",
        "difficulty": "Moderate",
        "questionNumber": 60,
        "questionText": "A patient has progressive memory impairment plus early visual hallucinations, cognitive fluctuations and parkinsonism. Which diagnosis is most consistent with this combination?",
        "optionA": "Dementia with Lewy bodies",
        "optionB": "Frontotemporal dementia without other features",
        "optionC": "Normal aging",
        "optionD": "Pure vascular peripheral neuropathy",
        "correctAnswer": "A",
        "explanation": "Early cognitive fluctuations, recurrent visual hallucinations and spontaneous parkinsonism are characteristic clinical features of dementia with Lewy bodies."
    }
];
